### ISSUE TITLE
Velocity Error

### ISSUE THREAD

**Issue by Innesity** [CapeCraft/TAB#4]
### Server version

Velocity 3.2.0

### TAB version

3.2.1

### Stack trace

[18:14:56] [Velocity Async Event Executor - #0/INFO] [tab]: Registering extra velocity packets...
[18:14:56] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to tab
java.lang.IllegalAccessError: class me.neznamy.tab.platforms.velocity.VelocityPacketRegistry tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.clientbound (me.neznamy.tab.platforms.velocity.VelocityPacketRegistry is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @acf859d; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
	at me.neznamy.tab.platforms.velocity.VelocityPacketRegistry.registerPackets(VelocityPacketRegistry.java:35) ~[?:?]
	at me.neznamy.tab.platforms.velocity.Main.isVersionSupported(Main.java:126) ~[?:?]
	at me.neznamy.tab.platforms.velocity.Main.onProxyInitialization(Main.java:79) ~[?:?]
	at me.neznamy.tab.platforms.velocity.Lmbda$31.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[run-velocity.jar:3.2.0-SNAPSHOT (git-f744b37a-b222)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[run-velocity.jar:3.2.0-SNAPSHOT (git-f744b37a-b222)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[run-velocity.jar:3.2.0-SNAPSHOT (git-f744b37a-b222)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by james090500** [comment]
https://github.com/CapeCraft/TAB/releases/tag/3.2.1
