### ISSUE TITLE
Velocity error

### ISSUE THREAD

**Issue by Alpho320** [CapeCraft/TAB#5]
### Server version

https://github.com/WiIIiam278/Velocity-NoChatSigning

### TAB version

3.3.1

### Stack trace

```
[00:21:00] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.2.0-SNAPSHOT-nochatsigning...
[00:21:00] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading localizations...
[00:21:00] [main/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[00:21:00] [main/WARN] [com.velocitypowered.proxy.config.VelocityConfiguration]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[00:21:00] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loading plugins...
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin authmevelocity 3.0.6 by xQuickGlare, 4drian3d
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin fastmotd 1.0.0 by hevav, mdxd44
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin luckperms 5.4.61 by Luck
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin huskchat 2.4.1-48e6069-indev by William278
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin litebans 2.11.3 by Ruan
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin skinsrestorer 14.2.8 by knat, AlexProgrammerDE, Blackfire62, McLive
[00:21:00] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin tab 3.3.1-SNAPSHOT by NEZNAMY
[00:21:00] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Loaded 7 plugins
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]:         __    
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]:   |    |__)   LuckPerms v5.4.61
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]:   |___ |      Running on Velocity - Velocity
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: 
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading configuration...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading storage provider... [MYSQL]
[00:21:01] [Velocity Async Event Executor - #0/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading messaging service... [SQL]
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Loading internal permission managers...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Performing initial data load...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [luckperms]: Successfully enabled. (took 492ms)
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]:  --- AuthMeVelocity ---
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: AuthServers: [login]
[00:21:01] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: LobbyServers: [lobbys]
[00:21:01] [Velocity Async Event Executor - #0/INFO] [fastmotd]: Hooked into ServerChannelInitializer
[00:21:01] [Velocity Async Event Executor - #0/ERROR] [fastmotd]: ****************************************
[00:21:01] [Velocity Async Event Executor - #0/WARN] [fastmotd]: The new FastMOTD update was found, please update.
[00:21:01] [Velocity Async Event Executor - #0/ERROR] [fastmotd]: https://github.com/Elytrium/FastMOTD/releases/
[00:21:01] [Velocity Async Event Executor - #0/ERROR] [fastmotd]: ****************************************
[00:21:01] [Velocity Async Event Executor - #0/INFO] [huskchat]: Enabled HuskChat version 2.4.1-48e6069-indev
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Using system locale (en)
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Loaded 4 templates from templates.yml!
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Loading SQL driver: mysql 8.0.29 (com.mysql.cj.jdbc.Driver)
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Connecting to database...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: litebans-pool - Starting...
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: litebans-pool - Start completed.
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Connected to MySQL database successfully (58.7 ms).
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: [Sync] Server name: litebans
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: [Sync] Server UUID: 356e304480c143a7820ee1ef5df2c2f1 <4>
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: Database connection fully initialized (71.9 ms).
[00:21:01] [Velocity Async Event Executor - #0/INFO] [litebans]: v2.11.3 enabled. Startup took 262 ms.
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m----------------------------------------------[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m    +==================+[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m    |   SkinsRestorer  |[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m    +==================+[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m----------------------------------------------[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [36;1m    Current version: [32;1m14.2.8[0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m    This is the latest version![0;39m
[00:21:01] [Velocity Task Scheduler - #8/INFO] [skinsrestorer]: [32;1m----------------------------------------------[0;39m
[00:21:02] [Velocity Async Event Executor - #0/INFO] [tab]: Registering extra velocity packets...
[00:21:02] [Velocity Async Event Executor - #0/INFO] [tab]: Successfully registered extra velocity packets!
[00:21:02] [Velocity Async Event Executor - #0/INFO] [tab]: Loaded packet hook in 19ms
[00:21:02] [Velocity Async Event Executor - #0/INFO] [tab]: Enabled in 47ms
[00:21:02] [Netty epoll Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[00:21:02] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (1.91s)!
[00:21:10] [Netty epoll Worker #3/INFO] [com.velocitypowered.proxy.connection.client.AuthSessionHandler]: [connected player] Luserr (/159.146.121.72:44266) has connected
[00:21:10] [Netty epoll Worker #3/WARN] [com.velocitypowered.proxy.connection.client.AuthSessionHandler]: UUID for Player Luserr mismatches! Chat/Commands signatures will not work correctly for this player!
[00:21:10] [Netty epoll Worker #3/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] Luserr -> login has connected
[00:21:10] [Netty epoll Worker #3/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] Luserr (/159.146.121.72:44266) has disconnected: An internal error occurred in your connection.
[00:21:10] [Netty epoll Worker #3/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] Luserr (/159.146.121.72:44266): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@4a1d22bf
io.netty.handler.codec.EncoderException: java.lang.UnsupportedOperationException: Unknown action 5
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at me.neznamy.tab.platforms.velocity.VelocityPipelineInjector$VelocityChannelDuplexHandler.write(VelocityPipelineInjector.java:60) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Unknown action 5
	at com.velocitypowered.proxy.protocol.packet.LegacyPlayerListItem.encode(LegacyPlayerListItem.java:157) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:54) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server.jar:3.2.0-SNAPSHOT-nochatsigning]
	... 17 more
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by james090500** [comment]
This fork is closed due to upstream having velocity support ish
